.TH "CADDY-TRUST" "1" "September 2021"
.SH NAME
.HP
caddy-trust \- Installs a CA certificate into local trust stores
.SH SYNOPSIS
.HP
caddy trust 
.SH DESCRIPTION
.PP
Adds a root certificate into the local trust stores. Intended for
development environments only.

Since Caddy will install its root certificates into the local trust
stores automatically when they are first generated, this command is
only necessary if you need to pre-install the certificates before
using them; for example, if you have elevated privileges at one
point but not later, you will want to use this command so that a
password prompt is not required later.

This command installs the root certificate only for Caddy's
default CA.

.SH SEE ALSO
.PP
\fBcaddy-adapt\fR(1), \fBcaddy-caddy\fR(1), \fBcaddy-environ\fR(1), \fBcaddy-file-server\fR(1), \fBcaddy-fmt\fR(1), \fBcaddy-hash-password\fR(1), \fBcaddy-help\fR(1), \fBcaddy-list-modules\fR(1), \fBcaddy-man\fR(1), \fBcaddy-reload\fR(1), \fBcaddy-reverse-proxy\fR(1), \fBcaddy-run\fR(1), \fBcaddy-start\fR(1), \fBcaddy-stop\fR(1), \fBcaddy-untrust\fR(1), \fBcaddy-validate\fR(1), \fBcaddy-version\fR(1), \fBcaddy\fR(1)
.SH DOCUMENTATION
.HP
Full documentation is available at: https://caddyserver.com/docs/
.SH VERSION
.HP
2.4.5-1
.SH BUGS
.HP
Report Bugs to: https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors