.TH "CADDY-FILE-SERVER" "1" "August 2021"
.SH NAME
.HP
caddy-file-server \- Spins up a production-ready file server
.SH SYNOPSIS
.HP
caddy file-server [--domain <example.com>] [--root <path>] [--listen <addr>] [--browse] [--access-log]
.SH DESCRIPTION
.PP 
A simple but production-ready file server. Useful for quick deployments,
demos, and development.

The listener's socket address can be customized with the --listen flag.

If a domain name is specified with --domain, the default listener address
will be changed to the HTTPS port and the server will use HTTPS. If using
a public domain, ensure A/AAAA records are properly configured before
using this option.

If --browse is enabled, requests for folders without an index file will
respond with a file listing.
.SH OPTIONS
.HP
\fB-access-log\fR <string>
.RS
Enable the access log
.RE 
.HP
\fB-browse\fR <string>
.RS
Enable directory browsing
.RE 
.HP
\fB-domain\fR <string>
.RS
Domain name at which to serve the files
.RE 
.HP
\fB-listen\fR <string>
.RS
The address to which to bind the listener
.RE 
.HP
\fB-root\fR <string>
.RS
The path to the root of the site
.RE 
.HP
\fB-templates\fR <string>
.RS
Enable template rendering
.RE  
.SH SEE ALSO
caddy-adapt(1), caddy-environ(1), caddy-fmt(1), caddy-hash-password(1), caddy-help(1), caddy-list-modules(1), caddy-reload(1), caddy-reverse-proxy(1), caddy-run(1), caddy-start(1), caddy-stop(1), caddy-trust(1), caddy-untrust(1), caddy-validate(1)
.HP
.SH DOCUMENTATION
Full documentation is available at:
https://caddyserver.com/docs/
.SH BUGS
.HP
Report Bugs to https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors
