.TH "CADDY-ENVIRON" "1" "August 2021"
.SH NAME
.HP
caddy-environ \- Prints the environment
.SH SYNOPSIS
.HP
caddy environ 
.SH SEE ALSO
caddy-adapt(1), caddy-file-server(1), caddy-fmt(1), caddy-hash-password(1), caddy-help(1), caddy-list-modules(1), caddy-reload(1), caddy-reverse-proxy(1), caddy-run(1), caddy-start(1), caddy-stop(1), caddy-trust(1), caddy-untrust(1), caddy-validate(1)
.HP
.SH DOCUMENTATION
Full documentation is available at:
https://caddyserver.com/docs/
.SH BUGS
.HP
Report Bugs to https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors
