.TH "CADDY-STOP" "1" "September 2021"
.SH NAME
.HP
caddy-stop \- Gracefully stops a started Caddy process
.SH SYNOPSIS
.HP
caddy stop 
.SH DESCRIPTION
.PP
Stops the background Caddy process as gracefully as possible.

It requires that the admin API is enabled and accessible, since it will
use the API's /stop endpoint. The address of this request can be
customized using the --address flag if it is not the default.
.SH OPTIONS
.HP
\fB-address\fR <string>
.RS
The address to use to reach the admin API endpoint, if not the default
.RE
.SH SEE ALSO
.PP
\fBcaddy-adapt\fR(1), \fBcaddy-caddy\fR(1), \fBcaddy-environ\fR(1), \fBcaddy-file-server\fR(1), \fBcaddy-fmt\fR(1), \fBcaddy-hash-password\fR(1), \fBcaddy-help\fR(1), \fBcaddy-list-modules\fR(1), \fBcaddy-man\fR(1), \fBcaddy-reload\fR(1), \fBcaddy-reverse-proxy\fR(1), \fBcaddy-run\fR(1), \fBcaddy-start\fR(1), \fBcaddy-trust\fR(1), \fBcaddy-untrust\fR(1), \fBcaddy-validate\fR(1), \fBcaddy-version\fR(1), \fBcaddy\fR(1)
.SH DOCUMENTATION
.HP
Full documentation is available at: https://caddyserver.com/docs/
.SH VERSION
.HP
2.4.3
.SH BUGS
.HP
Report Bugs to: https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors