.TH "CADDY-START" "1" "September 2021"
.SH NAME
.HP
caddy-start \- Starts the Caddy process in the background and then returns
.SH SYNOPSIS
.HP
caddy start [--config <path> [--adapter <name>]] [--envfile <path>] [--watch] [--pidfile <file>]
.SH DESCRIPTION
.PP
Starts the Caddy process, optionally bootstrapped with an initial config file.
This command unblocks after the server starts running or fails to run.

If --envfile is specified, an environment file with environment variables in
the KEY=VALUE format will be loaded into the Caddy process.

On Windows, the spawned child process will remain attached to the terminal, so
closing the window will forcefully stop Caddy; to avoid forgetting this, try
using 'caddy run' instead to keep it in the foreground.
.SH OPTIONS
.HP
\fB--adapter\fR
.RS
Name of config adapter to apply
.RE
.HP
\fB--config\fR
.RS
Configuration file
.RE
.HP
\fB--envfile\fR
.RS
Environment file to load
.RE
.HP
\fB--pidfile\fR
.RS
Path of file to which to write process ID
.RE
.HP
\fB--watch\fR
.RS
Reload changed config file automatically
.RE
.SH SEE ALSO
.PP
\fBcaddy-adapt\fR(1), \fBcaddy-caddy\fR(1), \fBcaddy-environ\fR(1), \fBcaddy-file-server\fR(1), \fBcaddy-fmt\fR(1), \fBcaddy-hash-password\fR(1), \fBcaddy-help\fR(1), \fBcaddy-list-modules\fR(1), \fBcaddy-man\fR(1), \fBcaddy-reload\fR(1), \fBcaddy-reverse-proxy\fR(1), \fBcaddy-run\fR(1), \fBcaddy-stop\fR(1), \fBcaddy-trust\fR(1), \fBcaddy-untrust\fR(1), \fBcaddy-validate\fR(1), \fBcaddy-version\fR(1), \fBcaddy\fR(1)
.SH DOCUMENTATION
.HP
Full documentation is available at: https://caddyserver.com/docs/
.SH VERSION
.HP
2.4.5-1
.SH BUGS
.HP
Report Bugs to: https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors