.TH "CADDY-ADAPT" "1" "September 2021"
.SH NAME
.HP
caddy-adapt \- Adapts a configuration to Caddy's native JSON
.SH SYNOPSIS
.HP
caddy adapt --config <path> [--adapter <name>] [--pretty] [--validate]
.SH DESCRIPTION
.PP
Adapts a configuration to Caddy's native JSON format and writes the
output to stdout, along with any warnings to stderr.

If --pretty is specified, the output will be formatted with indentation
for human readability.

If --validate is used, the adapted config will be checked for validity.
If the config is invalid, an error will be printed to stderr and a non-
zero exit status will be returned.
.SH OPTIONS
.HP
\fB-adapter\fR <string>
.RS
Name of config adapter
.RE
.HP
\fB-config\fR <string>
.RS
Configuration file to adapt (required)
.RE
.HP
\fB-pretty\fR <string>
.RS
Format the output for human readability
.RE
.HP
\fB-validate\fR <string>
.RS
Validate the output
.RE
.SH SEE ALSO
.PP
\fBcaddy-caddy\fR(1), \fBcaddy-environ\fR(1), \fBcaddy-file-server\fR(1), \fBcaddy-fmt\fR(1), \fBcaddy-hash-password\fR(1), \fBcaddy-help\fR(1), \fBcaddy-list-modules\fR(1), \fBcaddy-man\fR(1), \fBcaddy-reload\fR(1), \fBcaddy-reverse-proxy\fR(1), \fBcaddy-run\fR(1), \fBcaddy-start\fR(1), \fBcaddy-stop\fR(1), \fBcaddy-trust\fR(1), \fBcaddy-untrust\fR(1), \fBcaddy-validate\fR(1), \fBcaddy-version\fR(1), \fBcaddy\fR(1)
.SH DOCUMENTATION
.HP
Full documentation is available at: https://caddyserver.com/docs/
.SH VERSION
.HP
2.4.3
.SH BUGS
.HP
Report Bugs to: https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors