.TH "CADDY-RELOAD" "1" "September 2021"
.SH NAME
.HP
caddy-reload \- Changes the config of the running Caddy instance
.SH SYNOPSIS
.HP
caddy reload --config <path> [--adapter <name>] [--address <interface>]
.SH DESCRIPTION
.PP
Gives the running Caddy instance a new configuration. This has the same effect
as POSTing a document to the /load API endpoint, but is convenient for simple
workflows revolving around config files.

Since the admin endpoint is configurable, the endpoint configuration is loaded
from the --address flag if specified; otherwise it is loaded from the given
config file; otherwise the default is assumed.
.SH OPTIONS
.HP
\fB-adapter\fR <string>
.RS
Name of config adapter to apply
.RE
.HP
\fB-address\fR <string>
.RS
Address of the administration listener, if different from config
.RE
.HP
\fB-config\fR <string>
.RS
Configuration file (required)
.RE
.HP
\fB-force\fR <string>
.RS
Force config reload, even if it is the same
.RE
.SH SEE ALSO
.PP
\fBcaddy-adapt\fR(1), \fBcaddy-caddy\fR(1), \fBcaddy-environ\fR(1), \fBcaddy-file-server\fR(1), \fBcaddy-fmt\fR(1), \fBcaddy-hash-password\fR(1), \fBcaddy-help\fR(1), \fBcaddy-list-modules\fR(1), \fBcaddy-man\fR(1), \fBcaddy-reverse-proxy\fR(1), \fBcaddy-run\fR(1), \fBcaddy-start\fR(1), \fBcaddy-stop\fR(1), \fBcaddy-trust\fR(1), \fBcaddy-untrust\fR(1), \fBcaddy-validate\fR(1), \fBcaddy-version\fR(1), \fBcaddy\fR(1)
.SH DOCUMENTATION
.HP
Full documentation is available at: https://caddyserver.com/docs/
.SH VERSION
.HP
2.4.3
.SH BUGS
.HP
Report Bugs to: https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors