.TH "CADDY-FILE-SERVER" "1" "September 2021"
.SH NAME
.HP
caddy-file-server \- Spins up a production-ready file server
.SH SYNOPSIS
.HP
caddy file-server [--domain <example.com>] [--root <path>] [--listen <addr>] [--browse] [--access-log]
.SH DESCRIPTION
.PP
A simple but production-ready file server. Useful for quick deployments,
demos, and development.

The listener's socket address can be customized with the --listen flag.

If a domain name is specified with --domain, the default listener address
will be changed to the HTTPS port and the server will use HTTPS. If using
a public domain, ensure A/AAAA records are properly configured before
using this option.

If --browse is enabled, requests for folders without an index file will
respond with a file listing.
.SH OPTIONS
.HP
\fB-access-log\fR <string>
.RS
Enable the access log
.RE
.HP
\fB-browse\fR <string>
.RS
Enable directory browsing
.RE
.HP
\fB-domain\fR <string>
.RS
Domain name at which to serve the files
.RE
.HP
\fB-listen\fR <string>
.RS
The address to which to bind the listener
.RE
.HP
\fB-root\fR <string>
.RS
The path to the root of the site
.RE
.HP
\fB-templates\fR <string>
.RS
Enable template rendering
.RE
.SH SEE ALSO
.PP
\fBcaddy-adapt\fR(1), \fBcaddy-caddy\fR(1), \fBcaddy-environ\fR(1), \fBcaddy-fmt\fR(1), \fBcaddy-hash-password\fR(1), \fBcaddy-help\fR(1), \fBcaddy-list-modules\fR(1), \fBcaddy-man\fR(1), \fBcaddy-reload\fR(1), \fBcaddy-reverse-proxy\fR(1), \fBcaddy-run\fR(1), \fBcaddy-start\fR(1), \fBcaddy-stop\fR(1), \fBcaddy-trust\fR(1), \fBcaddy-untrust\fR(1), \fBcaddy-validate\fR(1), \fBcaddy-version\fR(1), \fBcaddy\fR(1)
.SH DOCUMENTATION
.HP
Full documentation is available at: https://caddyserver.com/docs/
.SH VERSION
.HP
2.4.3
.SH BUGS
.HP
Report Bugs to: https://github.com/caddyserver/caddy
.SH COPYRIGHT
.HP
(c) Matthew Holt and The Caddy Authors